// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ActionButtom: typeof import('./src/components/main_chat/ActionButtom.vue')['default']
    DialogBoard: typeof import('./src/components/main_chat/DialogBoard.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconHuman: typeof import('./src/components/icons/IconHuman.vue')['default']
    IconRobort: typeof import('./src/components/icons/IconRobort.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTittle: typeof import('./src/components/icons/IconTittle.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    KcgOption: typeof import('./src/components/main_chat/KcgOption.vue')['default']
    KnowledgeCard: typeof import('./src/components/tree_generate/KnowledgeCard.vue')['default']
    NormOption: typeof import('./src/components/main_chat/NormOption.vue')['default']
    TaskButtom: typeof import('./src/components/main_chat/TaskButtom.vue')['default']
    TreeBoard: typeof import('./src/components/tree_generate/TreeBoard.vue')['default']
  }
}

export { }
